forge "http://forge.puppetlabs.com"

mod "icinga2",
  :git => 'https://github.com/Icinga/puppet-icinga2-rewrite.git',
  :ref => 'v0.8.0'
mod "icingaweb2",
  :git => 'https://github.com/Icinga/puppet-icingaweb2.git'
