forge "http://forge.puppetlabs.com"

mod "puppetlabs/apache"
mod "puppetlabs/apt"
mod "puppetlabs/stdlib"
mod "puppetlabs/concat"
mod "binford2k/drupal", "0.0.3"
mod "puppetlabs/mysql"
mod "puppetlabs/postgresql"
mod "camptocamp/openldap", "1.14.0"
mod "herculesteam/augeasproviders_core"
mod "herculesteam/augeasproviders_shellvar"
mod "puppetlabs/chocolatey"
mod "puppetlabs/powershell", "2.0.2"
mod "theforeman/puppet"
mod "puppet/extlib"
mod "puppetlabs/inifile"
mod "jriviere/windows_ad"
mod "puppetlabs/puppetdb"

mod "icinga2",
  :git => 'https://github.com/Icinga/puppet-icinga2-rewrite.git',
  :ref => 'v0.7.0'
mod "icingaweb2",
  :git => 'https://github.com/Icinga/puppet-icingaweb2.git'
